global:
  resolve_timeout: 5m

route:
  receiver: 'email-alert'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'your-email@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'alertmanager@example.com'
        auth_password: 'yourpassword'
        auth_identity: 'alertmanager@example.com'
        require_tls: true
